### ISSUE TITLE
No time on OS X

### ISSUE THREAD

**Issue by Zorgatone** [JoeFyhrCeesay/time-status#3]
Just installed `time-status`.

I don't see the time anywhere on `atom`.

I'm on latest `atom` on latest `Mac OS X` `El Capitan`

**Comment by JoeFyhrCeesay** [comment]
Thank you for reporting this. I will look into it as soon as I have time.

**Comment by gera2ld** [comment]
Same issue, got error message like this:
```
Uncaught (in promise) TypeError: _ref.appendRight is not a function
    at time-status.TimeStatusView.attach (/Users/gerald/.atom/packages/time-status/lib/time-status-view.coffee:8:17)
    at /Users/gerald/.atom/packages/time-status/lib/time-status.coffee:12:15
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:488:32
```

**Comment by JoeFyhrCeesay** [comment]
The update to fix this issue is now live, thanks to @gera2ld.
